---
blank_issues_enabled: false
contact_links:
  - name: GitHub Community Support
    url: https://github.com/cerner/github_bot-ruby/discussions
    about: Please ask and answer questions and propose new features.