---
#CI will run on all pushes and PRs to verify validity of the code
name: CI

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']
  schedule:
    - cron: '0 1 * * SUN'
  workflow_dispatch:

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ruby:
        - 2.7
        - 3.0
        - 3.2
    name: Ruby-${{matrix.ruby}}
    continue-on-error: ${{matrix.ruby == 'head'}}
    steps:
    - name: Check out
      uses: actions/checkout@v2
    - name: Setup ruby and bundle
      uses: ruby/setup-ruby@v1
      with:
        bundler-cache: true
        ruby-version: ${{ matrix.ruby }}
    - name: Install dependencies
      run: bundle install --jobs 4 --retry 3
    - if: github.event_name == 'pull_request'
      name: Danger
      uses: danger/danger-js@9.1.8
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        # https://github.com/danger/danger-js/issues/557#issuecomment-664851950
        DANGER_DISABLE_TRANSPILATION: true
    - name: Run tests
      run: bundle exec rspec
    - name: Run Rubocop
      run: bundle exec rubocop
    